[project]
name = "mss"
version = "0.2.0"
description = ""
authors = [
    { name = "Lukas Breiter", email = "lukas.breiter@students.fhnw.ch" },
    { name = "Damian Szedalik", email = "damian.szedalik@students.fhnw.ch" }
    ]
requires-python = ">=3.12,<=3.14"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pandas (>=3.0.1,<4.0.0)",
    "pyarrow (>=19.0.0,<20.0.0)",
    "networkx (>=3.6.1,<4.0.0)",
    "ipykernel (>=7.2.0,<8.0.0)",
    "notebook (>=7.5.4,<8.0.0)",
    "numpy (>=2.4.2,<3.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "pyyaml (>=6.0,<7.0)",
    "mesa>=3.5.1",
    "funkybob>=2023.12.0",
]

[project.scripts]
mss-run = "mss.cli.run_coupled_simulation:main"
mss-visualize = "mss.cli.visualize_results:main"
mss-calibrate = "mss.cli.run_single_ward_calibration:main"
mss-calibrate-batch = "mss.cli.run_single_ward_batch:main"
mss-sweep = "mss.cli.run_parameter_sweep:main"

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "pre-commit>=3.6.0",
    "uvicorn>=0.27.0",
    "black (>=26.1.0,<27.0.0)",
    "ruff (>=0.15.4,<0.16.0)",
]

[tool.uv]
package = true

[build-system]
requires = ["uv_build>=0.10.8,<0.11.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--junitxml=report.xml"

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.black]
line-length = 100
target-version = ["py312"]
