mindmap
  root((Antibiotikaresistenzen))
    Externe Einfluessfaktoren
      Gemeinschaft_Umwelt
        Krankenhausaufnahmen
        Besiedlungsdruck_der_Bevölkerung
      Langzeitpflege_Pflegeheime
        Patienteneinweisungen
        Krankenhausübergreifende_Ausbreitung
      Mobilität_Reisen
        Veränderung_des_Resistenzpools
        Vernetzung_entfernter_Einrichtungen
      Landwirtschaft
        Antibiotikaeinsatz_in_der_Tierhaltung
      Markt_Entwicklung
        Diagnostikmarkt_Geschwindigkeit
        Entwicklung_neuer_Wirkstoffklassen
    Regulierung_und_Politik
      Behörden_Regulatoren
        Öffentliche_Gesundheitsüberwachung
        Screening_Richtlinien
        Antibiotika_Stewardship_Vorgaben
      Öffentliches_Gesundheitswesen
        Testkapazitäten
        Isolationsmaßnahmen
      Strategien
        Antibiotika_Leitlinien
        Wahl_der_Wirkstoffklassen
    Krankenhaus_Infrastruktur
      Einrichtung
        Fachabteilungen_Normalstation_Intensiv
        Bettenkapazität_und_Isolierzimmer
        Personalstärke_Reinigung_und_Hygiene
      Betriebliche_Abläufe
        Aufnahmemanagement
        Entlassungen_in_die_Gemeinschaft
        Patientenverlegung_zwischen_Kliniken
        Verweildauer_im_System
    Patientenfaktoren
      Demografie_Zustand
        Alter_Anfälligkeit_und_Immunsystem
        Schweregrad_der_Erkrankung
        Immunsstatus_und_Abwehrkraft
        Kooperation_des_Patienten_Compliance
      Klinische_Historie
        Vorbefunde_und_Vorgeschichte
        Frühere_Antibiotikatherapien
        Vorherige_Infektionen
        Therapietreue_Adhärenz
    Übertragung_und_Kontrolle
      Infektionswege
        Kontaktnetzwerke_im_Krankenhaus
        Umweltbelastung_und_Kontamination
        Besiedlungsdruck
        Übertragungswahrscheinlichkeit
      Prävention
        Screening_und_Schnelldiagnostik
        Frühzeitige_Erkennung_Detektionsrate
        Isolierung_von_Keimträgern
        Händehygiene_und_Schutzausrüstung
        Flächendesinfektion
    Biologische_Mechanismen
      Dynamik_im_Wirt
        Bakterienpopulation_und_Last
        Stammvielfalt_Diversität
        Anteil_resistenter_Erreger
        Dominante_Genotypen
      Antibiotikawirkung
        Dosierung_und_Therapiephase
        Abtötungsrate_durch_Wirkstoffe
        Unvollständige_Behandlung
      Evolution_Selektion
        Selektionsdruck_durch_Wirkstoffe
        Mutationsrate_und_Genetischer_Austausch_HGT
        Anpassungsfähigkeit_Fitness
      Resistenzmechanismen
        Effluxpumpen_Ausschleusung
        Modifikation_der_Zielstruktur
        Reduzierte_Permeabilität_Durchlässigkeit
        Virulenz_und_Anheftung
      Klinische_Folgen
        Therapieversagen
        Dauer_der_Besiedlung
        Sterblichkeitsrisiko
        Immunologische_Erregerelimination
