mindmap
  root((Antibiotikaresistenz))
    Krankenhaus
      Spital_Netzwerk
        Aufnahme
        Entlassung
        Verlegung
      Abteilungen
        Normalstation_WARD
        Intensivstation_ICU
      Umgebungsparameter
        Hygiene
        Isolation
        Erkennungsrate
        Diagnostikgeschwindigkeit
      Antibiotika_Policy
        ABX_Nutzung
        ABX_Klasse
        Dosierung
    Patient_Interface
      Demografie
        Alter
        Anfaelligkeit
      Immunsystem
        Immunstaerke
        Immunstatus
      Verhalten
        Compliance
        Adhaerenz
        Soziabilitaet
      Krankengeschichte
        Frueherer_ABX_Einsatz
        Fruehereinfektionen
      Zustand
        Traegerstatus_S_oder_C
        Behandlungsphase
      Mikro_Outputs_taeglich
        Resistenzanteil
        Dominanter_Genotyp
        Relative_Transmissibilitaet
        Clearance_Wahrscheinlichkeit
        Schweregrad_Modifikator
        Letalitaets_Modifikator
    Uebertragung
      Kolonisierungsdruck_carrier_force
      Transmissionswahrscheinlichkeit_p_colonize
      Clearance_C_nach_S
    Mikro_Evolution
      Genomstruktur_14_Gene
        Wachstum
          GROWTH_BASE
          METABOLIC_OPTIMIZATION
        Resistenzmechanismen
          EFFLUX_PUMPS
          TARGET_MODIFICATION
          PERMEABILITY_REDUCTION
        Virulenz_und_Persistenz
          VIRULENCE
          STEALTH
          ADHESION
        Evolvierbarkeit
          MUTATION_RATE_MODIFIER
          HGT_COMPETENCE
        Lebenszyklus_und_Persistenz
          DNA_REPAIR
          DORMANCY_PROPENSITY
          STRESS_RESPONSE
          DAMAGE_TOLERANCE
      Tagessimulation_12_Schritte
        Selektion
          Fitness_Berechnung
          ABX_Selektionsdruck
          Immunpressung
        Mutation
          Stressabhaengige_Rate
          Neue_Staemme_entstehen
        HGT_alle_3_Schritte
          Resistenzgen_Transfer
        Konsolidierung
          Pruning_unter_10
          Max_50_Staemme
      Outputs_an_Patient
        Resistenzanteil
        Genotyp_S_R1_R2_R3
        Transmissibilitaet
        Lethality
        Clearance_Wahrscheinlichkeit
